"""making database

Revision ID: d81de093152c
Revises: 7d75aa38f961
Create Date: 2023-06-26 15:10:53.745066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd81de093152c'
down_revision = '7d75aa38f961'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tranactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('investments', sa.Column('investment_name', sa.String(), nullable=True))
    op.add_column('investments', sa.Column('number_of_investments', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('investments', 'number_of_investments')
    op.drop_column('investments', 'investment_name')
    op.drop_table('tranactions')
    # ### end Alembic commands ###
